---
- hosts: servers
  tasks:
  - debug:
      msg: "SeLinux disabled. Please restart the server to apply changes."
    when: disable_selinux is defined and disable_selinux.changed == false
    
- hosts: servers
  tasks:
  - name: "Install Apache"
    yum:
      name: httpd
      state: present
    when: ansible_os_family == 'RedHat'
  
